In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
ds = pd.read_csv('TeluguMovies_dataset.csv')
ds.head(10)

,Unnamed: 0,Movie,Year,Certificate,Genre,Overview,Runtime,Rating,No.of.Ratings
0,0,Bahubali: The Beginning,2015.0,UA,"Action, Drama","In ancient India, an adventurous and darin...",159,8.1,99114
1,1,Baahubali 2: The Conclusion,2017.0,UA,"Action, Drama","When Shiva, the son of Bahubali, learns ab...",167,8.2,71458
2,2,1 - Nenokkadine,2014.0,UA,"Action, Thriller",A rock star must overcome his psychologica...,170,8.1,42372
3,3,Dhoom:3,2013.0,UA,"Action, Thriller","When Sahir, a circus entertainer trained i...",172,5.4,42112
4,4,Ra.One,2011.0,U,"Action, Adventure, Sci-Fi",When the titular antagonist of an action g...,156,4.6,37211
5,5,Dhoom:2,2006.0,UA,"Action, Thriller","Mr A, a fearless thief, steals valuable ar...",152,6.5,22983
6,6,Eega,2012.0,UA,"Action, Fantasy",A murdered man is reincarnated as a housef...,145,7.7,20636
7,7,Krrish 3,2013.0,U,"Action, Sci-Fi",Krrish and his scientist father have to sa...,152,5.2,20026
8,8,Arjun Reddy,2017.0,A,"Action, Drama, Romance","Arjun Reddy, a short tempered house surgeo...",182,8.1,19419
9,9,Rangasthalam,2018.0,UA,"Action, Drama",The fear of his elder brother's death star...,170,8.4,17559

In [4]:
col = ds.columns
col

Index(['Unnamed: 0', 'Movie', 'Year', 'Certificate', 'Genre', 'Overview',
       'Runtime', 'Rating', 'No.of.Ratings'],
      dtype='object')

In [7]:
X = ds.drop(columns=['Unnamed: 0', 'Certificate', 'Genre', 'Overview', 'Runtime', 'Rating', 'No.of.Ratings'])
X

                            Movie    Year
0         Bahubali: The Beginning  2015.0
1     Baahubali 2: The Conclusion  2017.0
2                 1 - Nenokkadine  2014.0
3                         Dhoom:3  2013.0
4                          Ra.One  2011.0
...                           ...     ...
1395                Maro Monagadu  1985.0
1396                     Jakkanna  2016.0
1397               Muvva Gopaludu  1987.0
1398        Ninney Ishta Paddaanu  2003.0
1399                     9 Nelalu  2001.0

[1400 rows x 2 columns]

In [9]:
Y = ds.drop(columns=['Unnamed: 0', 'Year', 'Certificate','Runtime','No.of.Ratings'])
Y

,Movie,Genre,Overview,Rating
0,Bahubali: The Beginning,"Action, Drama","In ancient India, an adventurous and darin...",8.1
1,Baahubali 2: The Conclusion,"Action, Drama","When Shiva, the son of Bahubali, learns ab...",8.2
2,1 - Nenokkadine,"Action, Thriller",A rock star must overcome his psychologica...,8.1
3,Dhoom:3,"Action, Thriller","When Sahir, a circus entertainer trained i...",5.4
4,Ra.One,"Action, Adventure, Sci-Fi",When the titular antagonist of an action g...,4.6
...,...,...,...,...
1395,Maro Monagadu,NaN,NaN,8.6
1396,Jakkanna,"Comedy, Drama",The movie is about an attempt by Sunil the...,6.3
1397,Muvva Gopaludu,"Drama, Romance",Muvva Gopaludu is a 1987 Indian Telugu fil...,7.8
1398,Ninney Ishta Paddaanu,NaN,Hero Charan (Tarun) a middle class family ...,5.9
1399,9 Nelalu,Drama,"Surendra marries Savitri, an orphan. In a ...",7.3

In [17]:
X.head()

                         Movie    Year
0      Bahubali: The Beginning  2015.0
1  Baahubali 2: The Conclusion  2017.0
2              1 - Nenokkadine  2014.0
3                      Dhoom:3  2013.0
4                       Ra.One  2011.0

In [18]:
Y.head()

,Movie,Genre,Overview,Rating
0,Bahubali: The Beginning,"Action, Drama","In ancient India, an adventurous and darin...",8.1
1,Baahubali 2: The Conclusion,"Action, Drama","When Shiva, the son of Bahubali, learns ab...",8.2
2,1 - Nenokkadine,"Action, Thriller",A rock star must overcome his psychologica...,8.1
3,Dhoom:3,"Action, Thriller","When Sahir, a circus entertainer trained i...",5.4
4,Ra.One,"Action, Adventure, Sci-Fi",When the titular antagonist of an action g...,4.6

In [20]:
X.shape, Y.shape

((1400, 2), (1400, 4))

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=20, test_size=0.3)

In [24]:
X_train.shape, Y_train.shape

((980, 2), (980, 4))

In [25]:
X_train.head()

                 Movie    Year
531      Swarnakamalam  1988.0
922        Athanokkade  2005.0
422   Superstar Kidnap  2015.0
1191          Dongaata  1996.0
471      Falaknuma Das  2019.0

In [26]:
Y_train.head()

,Movie,Genre,Overview,Rating
531,Swarnakamalam,"Drama, Musical, Romance",A painter who recently moved into the neig...,8.0
922,Athanokkade,"Action, Drama",NaN,6.8
422,Superstar Kidnap,Thriller,Three youngsters meet accidentally in a dr...,6.8
1191,Dongaata,Drama,A thief finds an innocent lady in the trai...,6.9
471,Falaknuma Das,"Action, Thriller",Set in the backdrop of the colonies of fal...,6.3

In [31]:
X_train.describe

<bound method NDFrame.describe of                  Movie    Year
531      Swarnakamalam  1988.0
922        Athanokkade  2005.0
422   Superstar Kidnap  2015.0
1191          Dongaata  1996.0
471      Falaknuma Das  2019.0
...                ...     ...
924     Amma Cheppindi  2006.0
1247         Galipatam  2014.0
271             Suryam  2004.0
474        Peda Rayudu  1995.0
1379               Run     NaN

[980 rows x 2 columns]>

In [32]:
Y_train.describe

<bound method NDFrame.describe of                  Movie                                Genre  \
531      Swarnakamalam  Drama, Musical, Romance
922        Athanokkade            Action, Drama
422   Superstar Kidnap                 Thriller
1191          Dongaata                    Drama
471      Falaknuma Das         Action, Thriller
...                ...                                  ...
924     Amma Cheppindi                    Drama
1247         Galipatam                    Drama
271             Suryam          Action, Romance
474        Peda Rayudu            Action, Drama
1379               Run   Action, Drama, Romance

                                               Overview  Rating
531       A painter who recently moved into the neig...     8.0
922                                                 NaN     6.8
422       Three youngsters meet accidentally in a dr...     6.8
1191      A thief finds an innocent lady in the trai...     6.9
471       Set in the backdrop of the colonies of fal...     6.3
...                                                 ...     ...
924       A sentimental drama where Sharwanand plays...     7.1
1247      Galipatam is the story of a couple Karthi ...     5.7
271       A man sets out to fulfil his mother's last...     5.1
474       Pedarayudu is the story of three brothers ...     7.2
1379      Sanju, a jobless computer engineer, who ha...     5.4

[980 rows x 4 columns]>

In [33]:
X_test.describe().round(2)

          Year
count   408.00
mean   2005.85
std      12.72
min    1932.00
25%    1998.75
50%    2009.00
75%    2016.00
max    2020.00

In [34]:
Y_test.describe().round(2)

       Rating
count  420.00
mean     6.23
std      1.33
min      1.10
25%      5.40
50%      6.40
75%      7.20
max      9.20