In [2]:
import pandas as pd

ds = pd.read_csv('Housing.csv')

ds.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
ds.columns = ds.columns.str.strip()
ds.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [4]:
ds["total_rooms"] = ds["bedrooms"] + ds["bathrooms"]

In [5]:
amenities = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

for col in amenities:
    ds[col] = ds[col].map({"yes": 1, "no": 0})

ds["total_amenities"] = ds[amenities].sum(axis=1)

In [6]:
ds["parking_per_bedroom"] = ds["parking"] / ds["bedrooms"]

In [7]:
ds["luxury_score"] = (
    ds["airconditioning"] +
    ds["guestroom"] +
    ds["basement"] +
    ds["hotwaterheating"] +
    ds["prefarea"]
)

In [8]:
ds["furnishingstatus"] = ds["furnishingstatus"].map({
    "unfurnished": 0,
    "semi-furnished": 1,
    "furnished": 2
})

In [9]:
binary_columns = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

for col in binary_columns:
    ds[col] = ds[col].map({"yes": 1, "no": 0})


ds["furnishingstatus"] = ds["furnishingstatus"].map({
    "unfurnished": 0,
    "semi-furnished": 1,
    "furnished": 2
})


ds["total_rooms"] = ds["bedrooms"] + ds["bathrooms"]

ds["area_per_story"] = ds["area"] / ds["stories"]

ds["total_amenities"] = ds[binary_columns].sum(axis=1)

ds["parking_per_bedroom"] = ds["parking"] / ds["bedrooms"]

ds["luxury_score"] = (
    ds["airconditioning"] +
    ds["guestroom"] +
    ds["basement"] +
    ds["hotwaterheating"] +
    ds["prefarea"]
)

ds.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,total_rooms,total_amenities,parking_per_bedroom,luxury_score,area_per_story
0,13300000,7420,4,2,3,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,6,0.0,0.500000,NaN,2473.333333
1,12250000,8960,4,4,4,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,8,0.0,0.750000,NaN,2240.000000
2,12250000,9960,3,2,2,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,5,0.0,0.666667,NaN,4980.000000
3,12215000,7500,4,2,2,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,6,0.0,0.750000,NaN,3750.000000
4,11410000,7420,4,1,2,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,5,0.0,0.500000,NaN,3710.000000