In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('hotel-booking-data.txt',delimiter='\t')

In [3]:
data

           Date       Company        Person Name  Room number
0    1-Jan-2022        Avamba  Anatole Ridehalgh       4008.0
1    1-Jan-2022          Fatz    Aldrich McKevin       2002.0
2    1-Jan-2022         Leexo    Stanley Hadrill       4012.0
3        Hotels           NaN                NaN          NaN
4    1-Jan-2022        Rhyzio       Lyndell Tice       1006.0
..          ...           ...                ...          ...
190   Cleartrip           NaN                NaN          NaN
191  1-Jan-2022      Fivechat     Corabella Saye       4008.0
192  1-Jan-2022       Innojam  Leandra Potapczuk       5002.0
193  1-Jan-2022  Twitterworks    Valentia Ledson       1010.0
194      Hotels           NaN                NaN          NaN

[195 rows x 4 columns]

In [4]:
data.head()

         Date Company        Person Name  Room number
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0
3      Hotels     NaN                NaN          NaN
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0

In [5]:
data.describe()

       Room number
count   153.000000
mean   3079.326797
std    1718.791186
min    1001.000000
25%    2001.000000
50%    3008.000000
75%    4010.000000
max    7002.000000

In [6]:
data['Company'].value_counts()

Company
Leexo           3
Quinu           3
Fivechat        3
Twitterlist     2
Jayo            2
               ..
Twitterwire     1
Skiba           1
Tagpad          1
Innojam         1
Twitterworks    1
Name: count, Length: 114, dtype: int64

In [7]:
data.dropna()

           Date       Company          Person Name  Room number
0    1-Jan-2022        Avamba    Anatole Ridehalgh       4008.0
1    1-Jan-2022          Fatz      Aldrich McKevin       2002.0
2    1-Jan-2022         Leexo      Stanley Hadrill       4012.0
4    1-Jan-2022        Rhyzio         Lyndell Tice       1006.0
5    1-Jan-2022         Eadel  Broderic Handscombe       3015.0
..          ...           ...                  ...          ...
186  1-Jan-2022        Tagpad       Stephani Lafee       1015.0
187  1-Jan-2022        Meevee      Victoria Lavery       7002.0
191  1-Jan-2022      Fivechat       Corabella Saye       4008.0
192  1-Jan-2022       Innojam    Leandra Potapczuk       5002.0
193  1-Jan-2022  Twitterworks      Valentia Ledson       1010.0

[134 rows x 4 columns]

In [8]:
data['2xRoom'] = data['Room number'] * 2

In [9]:
data

           Date       Company        Person Name  Room number   2xRoom
0    1-Jan-2022        Avamba  Anatole Ridehalgh       4008.0   8016.0
1    1-Jan-2022          Fatz    Aldrich McKevin       2002.0   4004.0
2    1-Jan-2022         Leexo    Stanley Hadrill       4012.0   8024.0
3        Hotels           NaN                NaN          NaN      NaN
4    1-Jan-2022        Rhyzio       Lyndell Tice       1006.0   2012.0
..          ...           ...                ...          ...      ...
190   Cleartrip           NaN                NaN          NaN      NaN
191  1-Jan-2022      Fivechat     Corabella Saye       4008.0   8016.0
192  1-Jan-2022       Innojam  Leandra Potapczuk       5002.0  10004.0
193  1-Jan-2022  Twitterworks    Valentia Ledson       1010.0   2020.0
194      Hotels           NaN                NaN          NaN      NaN

[195 rows x 5 columns]

In [10]:
data.dropna(inplace=True)
data.head(20)

          Date      Company          Person Name  Room number   2xRoom
0   1-Jan-2022       Avamba    Anatole Ridehalgh       4008.0   8016.0
1   1-Jan-2022         Fatz      Aldrich McKevin       2002.0   4004.0
2   1-Jan-2022        Leexo      Stanley Hadrill       4012.0   8024.0
4   1-Jan-2022       Rhyzio         Lyndell Tice       1006.0   2012.0
5   1-Jan-2022        Eadel  Broderic Handscombe       3015.0   6030.0
6   1-Jan-2022         Oozz         Deina Harwin       2005.0   4010.0
7   1-Jan-2022     Innotype    Benyamin Crocetti       2001.0   4002.0
10  1-Jan-2022         Jayo      Tate Manntschke       3014.0   6028.0
13  1-Jan-2022    Riffpedia       Elianore Vigar       3002.0   6004.0
14  1-Jan-2022         Tazz        Alonso Mundee       4006.0   8012.0
16  1-Jan-2022   Browsezoom        Ysabel Lordon       6003.0  12006.0
17  1-Jan-2022       Skinte        Raff Verecker       3012.0   6024.0
19  1-Jan-2022  Twitterlist      Andrea Humpatch       4005.0   8010.0
21  1-Jan-2022   Shuffletag          Cammy Curle       2016.0   4032.0
22  1-Jan-2022         Geba         Howey Oseman       6001.0  12002.0
25  1-Jan-2022     Flipopia    Prince Coppenhall       2002.0   4004.0
26  1-Jan-2022    Topicblab         Noni Tarbett       1012.0   2024.0
27  1-Jan-2022      Feedmix          Bondon Tuny       3007.0   6014.0
28  1-Jan-2022    Skynoodle      Andros Cathcart       1008.0   2016.0
30  1-Jan-2022         Mita        Aubert Racher       4004.0   8008.0

In [11]:
data['Room number'].isna()

0      False
1      False
2      False
4      False
5      False
       ...
186    False
187    False
191    False
192    False
193    False
Name: Room number, Length: 134, dtype: bool

In [12]:
data.isnull().sum()

Date           0
Company        0
Person Name    0
Room number    0
2xRoom         0
dtype: int64

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 134 entries, 0 to 193
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         134 non-null    object
 1   Company      134 non-null    object
 2   Person Name  134 non-null    object
 3   Room number  134 non-null    float64
 4   2xRoom       134 non-null    float64
dtypes: float64(2), object(3)
memory usage: 6.3+ KB